### ISSUE TITLE
No index.html exists

### ISSUE THREAD

**Issue by tnguyen14** [zeyon/MarkdownHtmlPreview#1]
I just tried installing this plugin via Package Control. 

Upon using it the first time, I got this error:

```
Error in GitHubMarkdownPreview package:

[Errno 2] No such file or directory: '/Users/my-username/Library/Application Support/Sublime Text 3/Packages/MarkdownHtmlPreview/dist/index.html'
```

**Comment by jdhom** [comment]
![image](https://cloud.githubusercontent.com/assets/742568/6807228/352be07c-d21b-11e4-8f28-6717d8ba3767.png)

I have this issue with ST3 / OSX (yosemite).  I see, *Markdown HTML Preview* directory is missing
```/Users/foo.bar/Library/Application Support/Sublime Text 3/Packages/Markdown HTML Preview```

**Comment by naavis** [comment]
This is also happening on ST3 + Windows 8.
```
Error in GitHubMarkdownPreview package:

[Errno 2] No such file or directory:
'C:\\Users\\samuvuor\\AppData\\Roaming\\Sublime Text 3\\Packages\\Markdown HTML Preview\\dist\\index.html```
