### ISSUE TITLE
Does not work with ST 3

### ISSUE THREAD

**Issue by onury** [zeyon/MarkdownHtmlPreview#5]
When I hit `ctrl+shift+m` nothing happens.
If I run it from sublime command palette, I get this error:
```
error: Error in GitHubMarkdownPreview package:

[Errno 2] No such file or directory: '~/Library/Application Support/Sublime Text 3/Packages/Markdown HTML Preview/dist/index.html'
```

Sublime Text (stable channel) build 3065 (latest as of 4 Mar 2015)
Mac OS X 10.10.2

**Comment by saada** [comment]
:+1:

**Comment by dapepe** [comment]
Hi guys! I assume you both use OS X, right? I will investigate... Thanks for your feedback!

**Comment by saada** [comment]
I'm on OSX Yosemite

**Comment by onury** [comment]
Yes Yosemite 10.10.2

**Comment by CallMeKlep** [comment]
I'm getting the same thing on Windows 7.

    error: Error in GitHubMarkdownPreview package:
    [Errno 2] No such file or directory: '~/Library/Application Support/Sublime Text 3/Packages/Markdown HTML Preview/dist/index.html'

**Comment by nihilon** [comment]
I am having the smae issue with ST3 under Windows 7. Here's what I've got:

**The error message:**

    Error in GitHubMardownPreview package:

    [Errno 2] No such file or directory:
    'C:\\Users\\<my home directory>\\AppData\\Roaming\\Sublime Text 3\\Packages\\Markdown HTML Preview\\dist\\index.html'

So, I decided to create the missing directory. That had no effect. But, the error changes once you create the missing html file:

    Error in GitHubMarkdownPreview package:
    
    expected bytes, bytearray or buffer compatible object

Hopefully that helps.

**Comment by elmerehbi** [comment]
I am facing the same issue. Just installed it and tried it to get the same error on Ubuntu/Linux.

**Comment by hqgoldswan** [comment]
I have same issue when working ST3 under Windows 8 environment.

Error in GitHubMarkdownPreview package

[Errno 2] No such file or directory:
'C:\\User\\myname\\AppData\\Roaming\\Sublime Text 3\\Packages\\Markdown HTML Preview\\dist\\index.html

Do you guy have any workaround solution?

**Comment by nihilon** [comment]
@hqgoldswan: Actually, unfortunately, the only work around is to use a different preview plugin. I don't mean to be the dick here, but that's the only option that I am personally aware of.

**Comment by dapepe** [comment]
Obviously the package management in ST3 has changed. Instead of creating a directory, packages are now stored as .sublime-package files (which are basically ZIP files). This is why the directory is no longer created and the HTML template file is nowhere to be found.

I have updated the build script so that the HTML template is now directly included in the Python file. This means no external files need to be loaded, which in turn circumvents the initial problem. The update is online now.

Thanks for your feedback!
