### ISSUE TITLE
'#' character is translated to a twitter link

### ISSUE THREAD

**Issue by ghuser** [zeyon/MarkdownHtmlPreview#6]
Though the specific syntax seems to be recognised

~~~markdown
```bash
#list files
ls
```
~~~
The preview converts "#list files" to :

    <a href="http://twitter.com/search/%23list">#list</a> files

**Comment by dapepe** [comment]
Acknowledged - will probably do an update soon and fix this...

**Comment by dapepe** [comment]
Removed the twitter extension, should work now!
